//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressColony
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int AddressPostalCodeId { get; set; }
        public int AddressMunicipalityId { get; set; }
        public int AddressStateId { get; set; }
    
        public virtual AddressPostalCode AddressPostalCode { get; set; }
    }
}
