//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Id { get; set; }
        public string Street { get; set; }
        public string NumberExt { get; set; }
        public string NumberInt { get; set; }
        public Nullable<int> AddressColonyId { get; set; }
        public Nullable<int> AddressPostalCodeId { get; set; }
        public Nullable<int> AddressMunicipalityId { get; set; }
        public Nullable<int> AddressStateId { get; set; }
    
        public virtual AddressColony AddressColony { get; set; }
    }
}
