//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BayerEmployee : Person
    {
        public BayerEmployee()
        {
            this.MunicipalitiesXEmployee = new HashSet<MunicipalitiesXEmployee>();
        }
    
        public string IdB { get; set; }
    
        public virtual ICollection<MunicipalitiesXEmployee> MunicipalitiesXEmployee { get; set; }
    }
}
