//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Zone
    {
        public Cat_Zone()
        {
            this.AddressMunicipalities = new HashSet<AddressMunicipality>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string RegionName { get; set; }
    
        public virtual ICollection<AddressMunicipality> AddressMunicipalities { get; set; }
    }
}
