//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractSubdistributor
    {
        public ContractSubdistributor()
        {
            this.DistributorPurchases = new HashSet<DistributorPurchasesXContractSubdistributor>();
        }
    
        public int Id { get; set; }
        public string IdB { get; set; }
        public int ContractSubdistributorStatusId { get; set; }
        public int SubdistributorId { get; set; }
        public int GRVBayerEmployeeId { get; set; }
        public int RTVBayerEmployeeId { get; set; }
        public int Year { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string RegisteredZoneName { get; set; }
        public string RegisteredRegionName { get; set; }
        public string ContractFilePath { get; set; }
        public int DiscountType { get; set; }
        public decimal AmountGoalS1Pre { get; set; }
        public decimal AmountGoalS1 { get; set; }
        public decimal AmountGoalS2Pre { get; set; }
        public decimal AmountGoalS2 { get; set; }
        public decimal AmountGoalTotalPre { get; set; }
        public decimal AmountGoalTotal { get; set; }
        public decimal PurchaseTotalJan { get; set; }
        public decimal PurchaseTotalFeb { get; set; }
        public decimal PurchaseTotalMar { get; set; }
        public decimal PurchaseTotalApr { get; set; }
        public decimal PurchaseTotalMay { get; set; }
        public decimal PurchaseTotalJun { get; set; }
        public decimal PurchaseTotalJul { get; set; }
        public decimal PurchaseTotalAgo { get; set; }
        public decimal PurchaseTotalSep { get; set; }
        public decimal PurchaseTotalOct { get; set; }
        public decimal PurchaseTotalNov { get; set; }
        public decimal PurchaseTotalDic { get; set; }
        public decimal PurchaseTotalS1 { get; set; }
        public decimal PurchaseTotalS2 { get; set; }
        public decimal PurchaseTotal { get; set; }
    
        public virtual Cat_ContractSubdistributorStatus ContractSubdistributorStatus { get; set; }
        public virtual Subdistributor Subdistributor { get; set; }
        public virtual BayerEmployee GRVBayerEmployee { get; set; }
        public virtual BayerEmployee RTVBayerEmployee { get; set; }
        public virtual ICollection<DistributorPurchasesXContractSubdistributor> DistributorPurchases { get; set; }
        public virtual SubdistributorDiscountCoupon SubdistributorDiscountCoupon { get; set; }
        public virtual SubdistributorPromotionCoupon SubdistributorPromotionCoupon { get; set; }
    }
}
