//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorPurchasesXContractSubdistributor
    {
        public int Id { get; set; }
        public int ContractSubdistributorId { get; set; }
        public int DistributorId { get; set; }
        public decimal PurchaseJan { get; set; }
        public decimal PurchaseFeb { get; set; }
        public decimal PurchaseMar { get; set; }
        public decimal PurchaseApr { get; set; }
        public decimal PurchaseMay { get; set; }
        public decimal PurchaseJun { get; set; }
        public decimal PurchaseJul { get; set; }
        public decimal PurchaseAgo { get; set; }
        public decimal PurchaseSep { get; set; }
        public decimal PurchaseOct { get; set; }
        public decimal PurchaseNov { get; set; }
        public decimal PurchaseDic { get; set; }
        public decimal PurchaseTotal { get; set; }
        public decimal PurchaseTotalS1 { get; set; }
        public decimal PurchaseTotalS2 { get; set; }
        public decimal CouponSharePercentage { get; set; }
        public decimal CouponSharePercentageS1 { get; set; }
        public decimal CouponSharePercentageS2 { get; set; }
        public decimal CouponShareAmount { get; set; }
        public decimal CouponShareAmountS1 { get; set; }
        public decimal CouponShareAmountS2 { get; set; }
    
        public virtual ContractSubdistributor ContractSubdistributor { get; set; }
        public virtual Distributor Distributor { get; set; }
    }
}
