//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorBranchContact
    {
        public int Id { get; set; }
        public int DistributorBranchId { get; set; }
        public Nullable<int> Cat_DistributorBranchContactAreaId { get; set; }
        public string FullName { get; set; }
        public string Role { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneNumberExt { get; set; }
        public string CellPhone { get; set; }
        public string EMail { get; set; }
        public string AssistantFullName { get; set; }
        public string AssistantPhoneNumber { get; set; }
        public string AssistantPhoneNumberExt { get; set; }
        public string AssistantCellPhone { get; set; }
        public string AssistantEMail { get; set; }
    
        public virtual Cat_DistributorBranchContactArea DistributorBranchContactArea { get; set; }
        public virtual DistributorBranch DistributorBranch { get; set; }
    }
}
