//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributor
    {
        public Distributor()
        {
            this.DistributorUsers = new HashSet<DistributorEmployee>();
            this.DistributorContacts = new HashSet<DistributorContact>();
            this.CropsXMunicipality = new HashSet<DistributorCropsXMunicipality>();
            this.DistributorBranches = new HashSet<DistributorBranch>();
            this.Contracts = new HashSet<ContractDistributor>();
        }
    
        public int Id { get; set; }
        public string IdB { get; set; }
        public string BusinessName { get; set; }
        public string CommercialName { get; set; }
        public Nullable<int> AddressId { get; set; }
        public string WebSite { get; set; }
        public string GeolocationLongitude { get; set; }
        public string GeolocationLatitude { get; set; }
    
        public virtual ICollection<DistributorEmployee> DistributorUsers { get; set; }
        public virtual Address Address { get; set; }
        public virtual ICollection<DistributorContact> DistributorContacts { get; set; }
        public virtual ICollection<DistributorCropsXMunicipality> CropsXMunicipality { get; set; }
        public virtual ICollection<DistributorBranch> DistributorBranches { get; set; }
        public virtual ICollection<ContractDistributor> Contracts { get; set; }
        public virtual ContractDistributor CurrentContract { get; set; }
    }
}
