//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistributorCropsXMunicipality
    {
        public int Id { get; set; }
        public int AddressMunicipalityId { get; set; }
        public int AddressMunicipalityAddressStateId { get; set; }
        public int Cat_CropId { get; set; }
        public int DistributorId { get; set; }
    
        public virtual AddressMunicipality Municipality { get; set; }
        public virtual Cat_Crop Crop { get; set; }
        public virtual Distributor Distributor { get; set; }
    }
}
