//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubdistributorDiscountCoupon
    {
        public int Id { get; set; }
        public decimal CouponAmount { get; set; }
        public decimal CouponAmountS1 { get; set; }
        public decimal CouponAmountS2 { get; set; }
        public bool HasCoupon { get; set; }
        public bool HasCouponS1 { get; set; }
        public bool HasCouponS2 { get; set; }
        public bool IsCalculated { get; set; }
        public bool IsCalculatedS1 { get; set; }
        public bool IsCalculatedS2 { get; set; }
    
        public virtual ContractSubdistributor ContractSubdistributor { get; set; }
    }
}
