//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.RolesXUser = new HashSet<RolesXUser>();
        }
    
        public int Id { get; set; }
        public int Cat_UserStatusId { get; set; }
        public string NickName { get; set; }
        public string Salt { get; set; }
        public string Hash { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public int FailedLoginAttempts { get; set; }
        public Nullable<System.DateTime> LastPasswordChangeDate { get; set; }
        public string LoginToken { get; set; }
        public Nullable<System.DateTime> LoginTokenGeneratedDate { get; set; }
    
        public virtual ICollection<RolesXUser> RolesXUser { get; set; }
        public virtual Cat_UserStatus Cat_UserStatus { get; set; }
        public virtual Person Person { get; set; }
    }
}
